# ===============================
# APP
# ===============================
spring.application.name=proyecto
server.port=8080

# ===============================
# DATABASE - PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace_db
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# SECURITY - BASIC
# ===============================
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET:m0M3fZfHFgyvVSXkYq98AgHLCN+rcdpoYcXVaabhG1o=}
jwt.expiration=3600000
jwt.refreshExpiration=86400000

# ===============================
# MAIL
# ===============================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=c9701cde02b2d9
spring.mail.password=b2c13868be125d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mail.from=noreply@tuapp.com

# ===============================
# RABBITMQ
# ===============================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest