spring.application.name=proyecto
server.port=8080

# ===== PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace_db
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# application.properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===== Spring Security =====
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN

# Llave secreta para JWT (debe ser segura y no compartida públicamente)
# Poner la clave en una variable de entorno
jwt.secret=m0M3fZfHFgyvVSXkYq98AgHLCN+rcdpoYcXVaabhG1o= 
jwt.expiration=3600000
jwt.refreshExpiration=86400000

#Mail Automatico
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=c9701cde02b2d9
spring.mail.password=b2c13868be125d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mail.from=noreply@tuapp.com